name: gofmt  
  
on:  
  push:  
    branches: [ "master" ]  
  pull_request:  
    branches: [ "master" ]  
  workflow_dispatch:  
  
jobs:  
  gofmt:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout  
        uses: actions/checkout@v4  
  
      - name: Check gofmt  
        run: |  
          out=$(gofmt -l cmd internal pkg tools)  
          if [ -n "$out" ]; then  
            echo "The following files are not gofmt-formatted:"  
            echo "$out"  
            exit 1  
          fi  
          echo "all files formatted"
