name: Build reva CLI for ARMv7  
  
on:  
  push:  
    branches: ["*"]  
  pull_request:  
  workflow_dispatch:  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout  
        uses: actions/checkout@v4  
        
      - name: Setup Go environment  
        uses: actions/setup-go@v4  
        with:  
          go-version-file: go.mod  
        
      - name: Install cross-compiler  
        run: |  
          sudo apt install gcc-arm-linux-gnueabihf  
        
      - name: Build reva CLI for ARMv7  
        run: |  
          CGO_ENABLED=1  
          CC=arm-linux-gnueabihf-gcc  
          GOARCH=arm  
          GOARM=7  
          go build -tags "sqlite_omit_load_extension" -ldflags "-extldflags '-static'" -o ./cmd/reva/reva-armv7 ./cmd/reva  
        
      - name: Upload artifact  
        uses: actions/upload-artifact@v4  
        with:  
          name: reva-armv7  
          path: ./cmd/reva/reva-armv7
